version: '3.8'

services:
  #only one service db
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER = user
      - POSTGRES_PASSWORD = password
      - POSTGRES_DB = postgresdb